### ISSUE TITLE
Nats Jetstream 

### ISSUE THREAD

**Issue by gedw99** [consultoriadigital-pt/dart-nats-streaming#1]
Does this work with nats Jetstream ?

the code uses the object name “Stan” so I presume it’s designed for the Nats Streaming platform and not Nats Jetstream ?

**Comment by brunoggt** [comment]
It's designed for the Nats Streaming platform :)

**Comment by gedw99** [comment]
Ok shame 

would have thought jwt stream is better in 100% of cases because it’s clustered whereas nats streaming is no clustered.

that’s part of the reason they made nats Jetstream

**Comment by brunoggt** [comment]
Thanks for sharing @gedw99.
We will look into it.

**Comment by gedw99** [comment]
you can also just compile the golang nats client into Flutter too

https://github.com/capitalpidx/flap compiles a DB and Server inside FLutter and so its easy to add NATS this way.

Its probably not your cup of tea, but another way to approach it.
